name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          activate-environment: pmd_beamphysics-dev
          environment-file: environment.yml

      #      - name: flake8
      #        shell: bash -l {0}
      #        run: |
      #          flake8 .

      - name: Install openPMD-beamphysics
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest tests
